language: node_js

node_js:
  - lts/*

cache: npm

script:
  - node ./node_modules/.bin/vue-cli-service test:unit --runInBand;

deploy:
  provider: gae
  keyfile: "credentials.tar.gz.enc"
  project: "modanisa.challenge"
  on: main
